// <auto-generated />
using Creational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Creational.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    [Migration("20230511203208_Parsing")]
    partial class Parsing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Creational.ParsingResult", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Exception")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Redirection")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sha1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("WithTaxobox")
                        .HasColumnType("bit");

                    b.HasKey("Title");

                    b.ToTable("ParsingResults");
                });

            modelBuilder.Entity("Creational.TaxoboxEntry", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Title", "Key");

                    b.ToTable("TaxoboxEntries");
                });

            modelBuilder.Entity("Creational.WikiPage", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Issue")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Ns")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.HasIndex("Step");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Creational.WikiPageContent", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Format")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sha1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("PageContents");
                });

            modelBuilder.Entity("Creational.ParsingResult", b =>
                {
                    b.HasOne("Creational.WikiPage", "Page")
                        .WithOne("Parsed")
                        .HasForeignKey("Creational.ParsingResult", "Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Creational.TaxoboxEntry", b =>
                {
                    b.HasOne("Creational.ParsingResult", "ParsedPage")
                        .WithMany("TaxoboxEntries")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParsedPage");
                });

            modelBuilder.Entity("Creational.WikiPageContent", b =>
                {
                    b.HasOne("Creational.WikiPage", "Page")
                        .WithOne("Content")
                        .HasForeignKey("Creational.WikiPageContent", "Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Creational.ParsingResult", b =>
                {
                    b.Navigation("TaxoboxEntries");
                });

            modelBuilder.Entity("Creational.WikiPage", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("Parsed");
                });
#pragma warning restore 612, 618
        }
    }
}
